### ISSUE TITLE
SQL injection problem

### ISSUE THREAD

**Issue by thehabbos007** [KUNszg/kbot#21]
Heyo, I saw the bot being used on a stream for spotify, and saw the code was open source. I looked into the spotify code and saw that - as far as I can tell - prepared statements were not used everywhere. Particularly here 
https://github.com/KUNszg/kbot/blob/f22b0438e8aadcd906c4c95b7719c9eeb1ef2dc5/lib/commands/spotify.js#L315-L319

I played around with this and found that a user can issue the following:
`kb spotify @."/**/or/**/username/**/like/**/'%szg'limit/**/1#`
and thereby run a query directly into the DB (here it fetches your user instead of "."). While the query is quite tame, one could imagine doing something like
`@." and 1=0 union all select access_token as username, "spoof", null, null from access_token` 
encoded correctly would be very bad because of the username being spewed out here
https://github.com/KUNszg/kbot/blob/f22b0438e8aadcd906c4c95b7719c9eeb1ef2dc5/lib/commands/spotify.js#L342

Just wanted to make sure you are aware of this :)

Thanks to https://www.twitch.tv/tony_handcock for letting me spam his chat thoroughly to see if this actually was an SQL injection (no access tokens were ever outputted)

**Comment by KUNszg** [comment]
Thank you for this issue, I am a beginner programmer and there is a lot of stuff in my code that is redundant or unsafe, but I am working on improving it as much as time lets me.  I replaced every query in my project with prepared statements and improved some code along the way. Thanks for your input once again.

**Comment by thehabbos007** [comment]
All good friend. Better you get to know it up front than someone misusing it :)
